-- 코드를 입력하세요
SELECT YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER, count(distinct a.USER_ID) as USERS
FROM USER_INFO a 
JOIN ONLINE_SALE b on a.user_id = b.user_id
WHERE GENDER IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
