SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE FAVORITES in (select max(FAVORITES)
                   from REST_INFO
                   group by FOOD_TYPE)
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE desc