SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I 
JOIN ANIMAL_OUTS O on I.ANIMAL_ID = O.ANIMAL_ID
WHERE SEX_UPON_INTAKE like 'Intact%' and (SEX_UPON_OUTCOME like 'Spayed%' or SEX_UPON_OUTCOME like 'Neutered%')
ORDER BY I.ANIMAL_ID;