# 서브쿼리 버전
# SELECT ITEM_ID, ITEM_NAME, RARITY
# FROM ITEM_INFO 
# WHERE ITEM_ID NOT IN (SELECT I.ITEM_ID
#     FROM ITEM_INFO I, ITEM_TREE T 
#     WHERE I.ITEM_ID = T.PARENT_ITEM_ID) 
# ORDER BY ITEM_ID desc;

SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
LEFT JOIN ITEM_TREE T ON I.ITEM_ID = T.PARENT_ITEM_ID
WHERE PARENT_ITEM_ID IS NULL
ORDER BY ITEM_ID DESC;