-- 코드를 입력하세요

SELECT month(START_DATE) as MONTH, CAR_ID, COUNT(HISTORY_ID) as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >= '2022-08-01' and START_DATE < '2022-11-01'
GROUP BY CAR_ID #해당 기간 동안의 월 별 자동차 ID별 총 대여횟수 리스트 출력
HAVING COUNT(CAR_ID) >= 5                
) AND START_DATE >= '2022-08-01' and START_DATE < '2022-11-01'
GROUP BY MONTH, CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH, CAR_ID desc

