-- 코드를 입력하세요
SELECT USER_ID
        , NICKNAME
        , CONCAT_WS(' ', CITY, STREET_ADDRESS1, STREET_ADDRESS2) AS '전체주소'
        , CONCAT_WS('-', LEFT(TLNO, 3), SUBSTRING(TLNO, 4, 4), RIGHT(TLNO, 4)) AS '전화번호'
FROM USED_GOODS_USER U
WHERE 1=1
AND U.USER_ID in (SELECT WRITER_ID
                 FROM USED_GOODS_BOARD
                 GROUP BY WRITER_ID
                 HAVING count(*) >= 3)
GROUP BY USER_ID
ORDER BY USER_ID desc
