SELECT D.ID, CASE 
    WHEN D.PERCENT <= 0.25 THEN 'CRITICAL'
    WHEN D.PERCENT <= 0.50 THEN 'HIGH'
    WHEN D.PERCENT <= 0.75 THEN 'MEDIUM'
    ELSE 'LOW' END AS COLONY_NAME
FROM (
    SELECT ID,
    PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS PERCENT
    FROM ECOLI_DATA
) D
ORDER BY ID;
