-- 코드를 입력하세요
SELECT F.FLAVOR
FROM FIRST_HALF AS F
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) as TOTAL_ORDER
     FROM JULY
     GROUP BY FLAVOR) AS J 
     ON F.FLAVOR = J.FLAVOR
ORDER BY (F.TOTAL_ORDER + J.TOTAL_ORDER) desc
LIMIT 3