-- 코드를 작성해주세요
SELECT GRADE.EMP_NO, 
    GRADE.EMP_NAME, 
    GRADE.GRADE, 
    CASE WHEN GRADE.GRADE = 'S' THEN GRADE.SAL * 0.2
        WHEN GRADE.GRADE = 'A' THEN GRADE.SAL * 0.15
        WHEN GRADE.GRADE = 'B' THEN GRADE.SAL * 0.1
        WHEN GRADE.GRADE = 'C' THEN 0
    END AS BONUS
FROM (SELECT E.EMP_NO, E.EMP_NAME, CASE 
            WHEN AVG(G.SCORE) >= 96 THEN 'S'
            WHEN AVG(G.SCORE) >= 90 THEN 'A'
            WHEN AVG(G.SCORE) >= 80 THEN 'B'
            ELSE 'C'
        END AS GRADE,
        E.SAL
FROM HR_EMPLOYEES E, HR_GRADE G
WHERE E.EMP_NO = G.EMP_NO
GROUP BY E.EMP_NO, E.EMP_NAME
) GRADE
ORDER BY GRADE.EMP_NO