-- 코드를 입력하세요
SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H on C.CAR_ID = H.CAR_ID
WHERE CAR_TYPE = '세단' AND START_DATE between '2022-10-01' and '2022-10-30'
GROUP BY CAR_ID
ORDER BY CAR_ID desc