SELECT CONCAT("/home/grep/src/", FILE.BOARD_ID, "/", FILE_ID, FILE_NAME, FILE_EXT) as FILE_PATH
FROM 
(SELECT BOARD_ID
FROM USED_GOODS_BOARD
ORDER BY VIEWS DESC
LIMIT 1) BOARD_VIEW, USED_GOODS_FILE FILE
WHERE BOARD_VIEW.BOARD_ID = FILE.BOARD_ID
ORDER BY FILE.FILE_ID desc;
