-- 코드를 작성해주세요
SELECT COUNT(*) AS FISH_COUNT, 
        MAX(F.LENGTH) AS MAX_LENGTH, 
        F.FISH_TYPE
FROM (SELECT ID, 
        FISH_TYPE, 
        CASE 
            WHEN LENGTH < 10 THEN 10
            WHEN LENGTH IS NULL THEN 10
        ELSE LENGTH END AS LENGTH
     FROM FISH_INFO
) F
GROUP BY F.FISH_TYPE
HAVING AVG(F.LENGTH) > 33
ORDER BY F.FISH_TYPE;
